### ISSUE TITLE
docker image out of date

### ISSUE THREAD

**Issue by travi** [greenkeeper-keeper/meta#3]
@cdaringe is there any way that the image you've hosted on docker hub could auto-update when the [reference-instance](https://github.com/greenkeeper-keeper/reference-instance) gets updated? it would make the link in the readme of this meta repo far more valuable. it would also align much better to the spirit of `greenkeeper-keeper`.

also, could you link to this repo rather than the old one that is now deprecated?

**Comment by cdaringe** [comment]
we'd probably need to pull my image down and have your CI push one up to keep it fresh?  id have no qualms with that.

also, the reference instance has no docs yet--should we hold off until those fill up?

**Comment by travi** [comment]
i dont think we need to involve ci because you can [set up an integration](https://docs.docker.com/docker-hub/builds/) between github and docker hub. is your `Dockerfile` set up in a way that can stand on its own, or would it be better to be part of the reference instance repo within this org? if you want it to be with the reference instance, just send a PR and i can try to figure out the integration so it gets published with a bot account.

as far as docs go for the reference instance, thats high on my list and might even be taken care of yet tonight. i plan to mainly link back to this meta repo, but also describe the required environment variables briefly. don't hesitate to let me know if you think other details would be helpful specifically for the reference instance.

**Comment by cdaringe** [comment]
> or would it be better to be part of the reference instance repo within this org?

it will have to live here or i would have to be a member of the gkk org, otherwise the githooks can't be wired up between services.  what a great feature dockerhub offers!

the dockerfile is:

```dockerfile
FROM node:alpine
ENV NODE_ENV=production
RUN mkdir -p /app
WORKDIR /app
COPY . /app
EXPOSE 8080
RUN npm install --prod
CMD ["npm", "start"]
```

so it should stand on its own pretty well i think!

**Comment by travi** [comment]
if you'd like to be a contributor beyond the dockerfile, i'm open to adding more contributors to the github org. i've already added you as a member to the docker hub org.

**Comment by cdaringe** [comment]
ya you can add me in 👍

**Comment by cdaringe** [comment]
anyway, i've tested the _new_ reference image.  it seems to be behaving normally, or at least consistently w/ the last.

truth be told, in the old image _and_ the new image, i'm seeing this:

"An attempt to merge this PR failed. Error: Not Found"

https://github.com/cdaringe/3d-adjacency/pull/13#issuecomment-301399930

Any clue there?

**Comment by travi** [comment]
great, you should have an invite to join the github org

**Comment by travi** [comment]
as far as the not found message goes, that type of message usually only shows up when two things have triggered `greenkeeper-keeper` to try to merge the PR and the second one fails because it has already been merged. any chance you are sending both `pull_request` and `status` webhooks? i could see having both enabled causing "problems" like this. using `status` actually causes more of this, but they are typically safe to ignore.

i havent documented `status` yet, but they seem to be working well. i'm hoping to deprecate `pull_request` in favor of `status` at some point. 

if you aren't sending both types of webhooks, could you open a new issue under `hapi-greenkeeper-keeper`? that would be a better place to track the discussion, even if we land on them just being safe to ignore.

btw, good choice for your bot :)

**Comment by cdaringe** [comment]
thanks :)  i moved the convo over to https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper/issues/140!

**Comment by cdaringe** [comment]
anyway, im confident we're shipping the new bits just fine!  i deprecated my old image: https://hub.docker.com/r/cdaringe/greenkeeper-keeper/. this issue is g2g
