### ISSUE TITLE
deploy to heroku button

### ISSUE THREAD

**Issue by travi** [greenkeeper-keeper/meta#4]
with a template: https://devcenter.heroku.com/articles/heroku-button

**Comment by travi** [comment]
also add a button for https://zeit.co/now

like https://deploy.now.sh/?repo=https://github.com/zeit/next.js/tree/master/examples/with-webpack-bundle-analyzer

**Comment by Kikobeats** [comment]
this could be easy the integration step. Thanks @travi for your effort!

**Comment by travi** [comment]
@Kikobeats thanks for the nudge. i added buttons to the [`reference-instance` repo](https://github.com/greenkeeper-keeper/reference-instance). i didnt add much for instruction, but the buttons should at least be functional. let me know if you try them out and run into any issues
