### ISSUE TITLE
sign up for gratipay integration

### ISSUE THREAD

**Issue by travi** [greenkeeper-keeper/meta#6]
not sure that this would have a very big impact on the project, but there's no reason not to sign up:
https://gratipay.news/integrating-npm-39333109419d

**Comment by chadwhitacre** [comment]
Gratipay founder here ... thanks for considering signing up, @travi! :)

Let me know if there are any questions I can answer. It's early days for our npm integration, but we are actively working on it and look forward to improving on it in the coming months. Would love to have you as an early adopter. ☺️

**Comment by travi** [comment]
thanks for reaching out. i'm hoping to take a look at this w/in the next few weeks, so i'll let you know if i run into anything

**Comment by travi** [comment]
https://github.com/gratipay/project-review/issues/497
